### ISSUE TITLE
Portable style - respect output directory, including environment variables

### ISSUE THREAD

**Issue by zaus** [enriquein/Cropper#1]
Bizarrely, the 'hidden' option to run as a portable app will cause it to override whatever setting you've placed for the `OutputDirectory`, even though that option was saved in the portable configuration.

https://github.com/enriquein/Cropper/blob/master/src/Cropper.Core/Configuration.cs#L98

Also, it doesn't expand environment variables as indicated in the [codeplex issue](https://cropper.codeplex.com/workitem/11001) -- would be great if it could do that.

**Comment by enriquein** [comment]
This was a personal fork of the project where I tried to tweak some stuff that never got pulled into the original repository. For any other requests, you're better off writing the official developers at their issue tracker: https://cropper.codeplex.com/discussions

Or do what I ended up doing: I switched to greenshot (http://getgreenshot.org/).

**Comment by zaus** [comment]
Yeah I was just going to fork it myself, but it bugs me to have a million versions of the same thing floating around.  Figured I'd give a pull request a shot.

**Comment by enriquein** [comment]
Sure, I'll merge it in.

**Comment by zaus** [comment]
Thanks.  Greenshot looks pretty nice too, but still doesn't support environment variables in the output path ;)
